//! Type definitions for intelligence service integration
//!
//! These types match the TypeScript intelligence service API at localhost:3002.
//! CRITICAL: Use `#[serde(rename_all = "kebab-case")]` for ChainCategory to match TypeScript.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Work category for chain naming - matches TypeScript ChainCategorySchema
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ChainCategory {
    BugFix,
    Feature,
    Refactor,
    Research,
    Cleanup,
    Documentation,
    Testing,
    Unknown,
}

/// Request to name a conversation chain
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainNamingRequest {
    pub chain_id: String,
    pub files_touched: Vec<String>,
    pub session_count: i32,
    pub recent_sessions: Vec<String>,

    // Enrichment fields (all Optional for backward compat)
    /// Aggregated tool usage across sessions: {"Read": 23, "Edit": 12}
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools_used: Option<HashMap<String, u32>>,
    /// User's stated intent from first message in chain
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_user_intent: Option<String>,
    /// Commit messages from the chain: ["feat: Add query engine"]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit_messages: Option<Vec<String>>,

    // A/B test fields - explicit separation for quality comparison
    /// First user message only (for A/B testing naming quality)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_user_message: Option<String>,
    /// Full conversation excerpt - all user messages (~8K chars)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_excerpt: Option<String>,
}

/// Response from chain naming endpoint
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainNamingResponse {
    pub chain_id: String,
    pub generated_name: String,
    pub category: ChainCategory,
    pub confidence: f32,
    pub model_used: String,
}

/// Cached chain metadata in SQLite
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainMetadata {
    pub chain_id: String,
    pub generated_name: Option<String>,
    pub category: Option<ChainCategory>,
    pub confidence: Option<f32>,
    pub generated_at: Option<DateTime<Utc>>,
    pub model_used: Option<String>,
}

// =============================================================================
// Chain Summary Types - matches TypeScript /api/intel/summarize-chain endpoint
// =============================================================================

/// Work status for chain summary - matches TypeScript WorkStatusSchema
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkStatus {
    InProgress,
    Complete,
    Paused,
    Abandoned,
}

/// Source of a workstream tag - existing from config or generated by model
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum WorkstreamTagSource {
    Existing,
    Generated,
}

/// A workstream tag with its source tracked
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkstreamTag {
    pub tag: String,
    pub source: WorkstreamTagSource,
}

/// Request to summarize a conversation chain with workstream tagging
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainSummaryRequest {
    pub chain_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_excerpt: Option<String>,
    pub files_touched: Vec<String>,
    pub session_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i64>,
    /// Existing workstreams from workstreams.yaml for hybrid tagging
    #[serde(skip_serializing_if = "Option::is_none")]
    pub existing_workstreams: Option<Vec<String>>,
}

/// Response from chain summary endpoint
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainSummaryResponse {
    pub chain_id: String,
    pub summary: String,
    pub accomplishments: Vec<String>,
    pub status: WorkStatus,
    pub key_files: Vec<String>,
    pub workstream_tags: Vec<WorkstreamTag>,
    pub model_used: String,
}

// =============================================================================
// GitOps Decision Types - Intelligent GitOps Level 0
// matches TypeScript /api/intel/gitops-decide endpoint
// =============================================================================

/// GitOps action types - what the agent recommends
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GitOpsAction {
    Commit, // Ready to commit - suggest message
    Push,   // Committed but unpushed - suggest push
    Notify, // Needs attention - explain why
    Wait,   // Not ready - explain why waiting
    Ask,    // Need user input before deciding
}

/// GitOps urgency levels
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GitOpsUrgency {
    Low,
    Medium,
    High,
}

/// Uncommitted file with status
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UncommittedFile {
    pub path: String,
    pub status: String, // "modified" | "added" | "deleted" | "renamed"
    pub lines_changed: Option<i32>,
}

/// Recent session context for GitOps decisions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentSessionContext {
    pub session_id: String,
    pub ended_at: Option<String>, // ISO8601, None if still active
    pub files_touched: Vec<String>,
    pub duration_minutes: i32,
    pub conversation_summary: Option<String>,
}

/// Active chain context for GitOps decisions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveChainContext {
    pub chain_id: String,
    pub workstream_tags: Vec<String>,
    pub accomplishments: Vec<String>,
    pub status: String, // "in_progress" | "complete" | "paused"
}

/// GitOps signals - input to agent from Rust daemon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitOpsSignals {
    // Git state
    pub uncommitted_files: Vec<UncommittedFile>,
    pub unpushed_commits: i32,
    pub current_branch: String,
    pub last_commit_timestamp: Option<String>, // ISO8601
    pub last_push_timestamp: Option<String>,   // ISO8601

    // Session context
    pub recent_session: Option<RecentSessionContext>,
    pub active_chain: Option<ActiveChainContext>,

    // User rules (promptable - natural language)
    pub user_rules: Vec<String>,

    // Time context
    pub hours_since_last_commit: Option<f64>,
    pub hours_since_last_push: Option<f64>,
}

/// GitOps decision - response from agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitOpsDecision {
    pub action: GitOpsAction,
    pub reason: String, // Human-readable explanation
    pub urgency: GitOpsUrgency,

    // Optional details based on action
    pub suggested_commit_message: Option<String>,
    pub files_to_stage: Option<Vec<String>>,
    pub coherence_assessment: Option<String>, // "auth feature", "mixed changes"

    pub model_used: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chain_category_serializes_kebab_case() {
        let category = ChainCategory::BugFix;
        let json = serde_json::to_string(&category).unwrap();
        assert_eq!(json, "\"bug-fix\"");
    }

    #[test]
    fn chain_category_deserializes_kebab_case() {
        let category: ChainCategory = serde_json::from_str("\"bug-fix\"").unwrap();
        assert_eq!(category, ChainCategory::BugFix);
    }

    #[test]
    fn chain_naming_request_serializes() {
        let request = ChainNamingRequest {
            chain_id: "test-123".to_string(),
            files_touched: vec!["src/main.rs".to_string()],
            session_count: 5,
            recent_sessions: vec![],
            tools_used: None,
            first_user_intent: None,
            commit_messages: None,
            first_user_message: None,
            conversation_excerpt: None,
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains("\"chain_id\":\"test-123\""));
        assert!(json.contains("\"session_count\":5"));
        // Optional fields should not appear when None
        assert!(!json.contains("tools_used"));
    }

    #[test]
    fn chain_naming_request_with_tools_used() {
        let mut tools = HashMap::new();
        tools.insert("Read".to_string(), 15);
        tools.insert("Edit".to_string(), 8);

        let request = ChainNamingRequest {
            chain_id: "test".to_string(),
            files_touched: vec![],
            session_count: 1,
            recent_sessions: vec![],
            tools_used: Some(tools),
            first_user_intent: None,
            commit_messages: None,
            first_user_message: None,
            conversation_excerpt: None,
        };

        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains("tools_used"));
        assert!(json.contains("\"Read\":15") || json.contains("\"Edit\":8"));
    }

    #[test]
    fn chain_naming_request_with_all_enrichment() {
        let mut tools = HashMap::new();
        tools.insert("Read".to_string(), 23);

        let request = ChainNamingRequest {
            chain_id: "full-test".to_string(),
            files_touched: vec!["src/lib.rs".to_string()],
            session_count: 10,
            recent_sessions: vec!["sess1".to_string()],
            tools_used: Some(tools),
            first_user_intent: Some("Port Python indexer to Rust".to_string()),
            commit_messages: Some(vec!["feat: Add query engine".to_string()]),
            first_user_message: Some("Help me port the Python indexer".to_string()),
            conversation_excerpt: Some(
                "Help me port...\nOk let's start...\nNow let's fix...".to_string(),
            ),
        };

        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains("tools_used"));
        assert!(json.contains("first_user_intent"));
        assert!(json.contains("Port Python indexer to Rust"));
        assert!(json.contains("commit_messages"));
        assert!(json.contains("feat: Add query engine"));
        assert!(json.contains("first_user_message"));
        assert!(json.contains("conversation_excerpt"));
    }

    #[test]
    fn chain_naming_response_deserializes() {
        let json = r#"{
            "chain_id": "abc",
            "generated_name": "Authentication refactor",
            "category": "refactor",
            "confidence": 0.85,
            "model_used": "claude-haiku-4-5-20251001"
        }"#;
        let response: ChainNamingResponse = serde_json::from_str(json).unwrap();
        assert_eq!(response.chain_id, "abc");
        assert_eq!(response.category, ChainCategory::Refactor);
        assert!((response.confidence - 0.85).abs() < 0.001);
    }

    #[test]
    fn all_chain_categories_deserialize() {
        let categories = vec![
            ("\"bug-fix\"", ChainCategory::BugFix),
            ("\"feature\"", ChainCategory::Feature),
            ("\"refactor\"", ChainCategory::Refactor),
            ("\"research\"", ChainCategory::Research),
            ("\"cleanup\"", ChainCategory::Cleanup),
            ("\"documentation\"", ChainCategory::Documentation),
            ("\"testing\"", ChainCategory::Testing),
            ("\"unknown\"", ChainCategory::Unknown),
        ];
        for (json, expected) in categories {
            let category: ChainCategory = serde_json::from_str(json).unwrap();
            assert_eq!(category, expected);
        }
    }

    #[test]
    fn chain_metadata_handles_optional_fields() {
        let metadata = ChainMetadata {
            chain_id: "test-123".to_string(),
            generated_name: None,
            category: None,
            confidence: None,
            generated_at: None,
            model_used: None,
        };
        let json = serde_json::to_string(&metadata).unwrap();
        assert!(json.contains("\"chain_id\":\"test-123\""));
    }

    // =========================================================================
    // Chain Summary Tests
    // =========================================================================

    #[test]
    fn work_status_serializes_snake_case() {
        assert_eq!(
            serde_json::to_string(&WorkStatus::InProgress).unwrap(),
            "\"in_progress\""
        );
        assert_eq!(
            serde_json::to_string(&WorkStatus::Complete).unwrap(),
            "\"complete\""
        );
        assert_eq!(
            serde_json::to_string(&WorkStatus::Paused).unwrap(),
            "\"paused\""
        );
        assert_eq!(
            serde_json::to_string(&WorkStatus::Abandoned).unwrap(),
            "\"abandoned\""
        );
    }

    #[test]
    fn work_status_deserializes_snake_case() {
        let status: WorkStatus = serde_json::from_str("\"in_progress\"").unwrap();
        assert_eq!(status, WorkStatus::InProgress);
    }

    #[test]
    fn workstream_tag_source_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&WorkstreamTagSource::Existing).unwrap(),
            "\"existing\""
        );
        assert_eq!(
            serde_json::to_string(&WorkstreamTagSource::Generated).unwrap(),
            "\"generated\""
        );
    }

    #[test]
    fn chain_summary_request_serializes() {
        let request = ChainSummaryRequest {
            chain_id: "test-chain".to_string(),
            conversation_excerpt: Some("Help me fix auth...".to_string()),
            files_touched: vec!["src/auth.rs".to_string()],
            session_count: 3,
            duration_seconds: Some(1800),
            existing_workstreams: Some(vec!["pixee".to_string(), "nickel".to_string()]),
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains("\"chain_id\":\"test-chain\""));
        assert!(json.contains("\"session_count\":3"));
        assert!(json.contains("\"existing_workstreams\""));
        assert!(json.contains("\"pixee\""));
    }

    #[test]
    fn chain_summary_request_skips_none_fields() {
        let request = ChainSummaryRequest {
            chain_id: "minimal".to_string(),
            conversation_excerpt: None,
            files_touched: vec![],
            session_count: 1,
            duration_seconds: None,
            existing_workstreams: None,
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(!json.contains("conversation_excerpt"));
        assert!(!json.contains("duration_seconds"));
        assert!(!json.contains("existing_workstreams"));
    }

    #[test]
    fn chain_summary_response_deserializes() {
        let json = r#"{
            "chain_id": "abc123",
            "summary": "Fixed OAuth redirect loop issues",
            "accomplishments": ["Identified bug", "Applied fix", "Added tests"],
            "status": "complete",
            "key_files": ["src/auth.rs", "src/oauth.rs"],
            "workstream_tags": [
                {"tag": "pixee", "source": "existing"},
                {"tag": "oauth-auth", "source": "generated"}
            ],
            "model_used": "claude-haiku-4-5-20251001"
        }"#;
        let response: ChainSummaryResponse = serde_json::from_str(json).unwrap();
        assert_eq!(response.chain_id, "abc123");
        assert_eq!(response.status, WorkStatus::Complete);
        assert_eq!(response.accomplishments.len(), 3);
        assert_eq!(response.workstream_tags.len(), 2);
        assert_eq!(response.workstream_tags[0].tag, "pixee");
        assert_eq!(
            response.workstream_tags[0].source,
            WorkstreamTagSource::Existing
        );
        assert_eq!(
            response.workstream_tags[1].source,
            WorkstreamTagSource::Generated
        );
    }

    // =========================================================================
    // GitOps Decision Tests
    // =========================================================================

    #[test]
    fn gitops_action_serializes_snake_case() {
        assert_eq!(
            serde_json::to_string(&GitOpsAction::Commit).unwrap(),
            "\"commit\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsAction::Push).unwrap(),
            "\"push\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsAction::Notify).unwrap(),
            "\"notify\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsAction::Wait).unwrap(),
            "\"wait\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsAction::Ask).unwrap(),
            "\"ask\""
        );
    }

    #[test]
    fn gitops_action_deserializes_snake_case() {
        let action: GitOpsAction = serde_json::from_str("\"commit\"").unwrap();
        assert_eq!(action, GitOpsAction::Commit);
    }

    #[test]
    fn gitops_urgency_serializes_snake_case() {
        assert_eq!(
            serde_json::to_string(&GitOpsUrgency::Low).unwrap(),
            "\"low\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsUrgency::Medium).unwrap(),
            "\"medium\""
        );
        assert_eq!(
            serde_json::to_string(&GitOpsUrgency::High).unwrap(),
            "\"high\""
        );
    }

    #[test]
    fn gitops_signals_serializes() {
        let signals = GitOpsSignals {
            uncommitted_files: vec![UncommittedFile {
                path: "src/auth.rs".to_string(),
                status: "modified".to_string(),
                lines_changed: Some(25),
            }],
            unpushed_commits: 3,
            current_branch: "main".to_string(),
            last_commit_timestamp: Some("2026-01-30T10:00:00Z".to_string()),
            last_push_timestamp: None,
            recent_session: Some(RecentSessionContext {
                session_id: "sess-123".to_string(),
                ended_at: Some("2026-01-30T11:00:00Z".to_string()),
                files_touched: vec!["src/auth.rs".to_string()],
                duration_minutes: 60,
                conversation_summary: Some("Fixed auth bug".to_string()),
            }),
            active_chain: None,
            user_rules: vec!["Push before end of day".to_string()],
            hours_since_last_commit: Some(2.5),
            hours_since_last_push: Some(6.0),
        };
        let json = serde_json::to_string(&signals).unwrap();
        assert!(json.contains("\"uncommitted_files\""));
        assert!(json.contains("\"unpushed_commits\":3"));
        assert!(json.contains("\"current_branch\":\"main\""));
        assert!(json.contains("\"user_rules\""));
    }

    #[test]
    fn gitops_decision_deserializes() {
        let json = r#"{
            "action": "commit",
            "reason": "Claude session ended 15 min ago. Changes form coherent unit.",
            "urgency": "medium",
            "suggested_commit_message": "feat(auth): Add JWT validation",
            "files_to_stage": ["src/auth.rs", "src/auth_test.rs"],
            "coherence_assessment": "Auth feature - all files related",
            "model_used": "claude-3-5-haiku-latest"
        }"#;
        let decision: GitOpsDecision = serde_json::from_str(json).unwrap();
        assert_eq!(decision.action, GitOpsAction::Commit);
        assert_eq!(decision.urgency, GitOpsUrgency::Medium);
        assert!(decision.suggested_commit_message.is_some());
        assert_eq!(
            decision.suggested_commit_message.unwrap(),
            "feat(auth): Add JWT validation"
        );
        assert_eq!(decision.files_to_stage.unwrap().len(), 2);
    }

    #[test]
    fn gitops_decision_deserializes_minimal() {
        let json = r#"{
            "action": "wait",
            "reason": "Work session is still active",
            "urgency": "low",
            "suggested_commit_message": null,
            "files_to_stage": null,
            "coherence_assessment": null,
            "model_used": "claude-3-5-haiku-latest"
        }"#;
        let decision: GitOpsDecision = serde_json::from_str(json).unwrap();
        assert_eq!(decision.action, GitOpsAction::Wait);
        assert_eq!(decision.urgency, GitOpsUrgency::Low);
        assert!(decision.suggested_commit_message.is_none());
    }
}
