"""Git commit sync to SQLite database.

Syncs git log data to SQLite for unified querying with file events and Claude sessions.
"""

import json
import logging
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from sqlite3 import Connection
from typing import Dict, List, Optional, TypedDict

logger = logging.getLogger(__name__)


# ============================================================================
# Type Definitions
# ============================================================================

@dataclass
class GitCommit:
    """Parsed git commit with all metadata."""
    hash: str                    # Full 40-char hash
    short_hash: str              # First 7 chars
    timestamp: datetime          # Author date
    author_name: str
    author_email: str
    message: str                 # Full commit message (first line)

    # File changes (parsed from --name-status)
    files_changed: List[str]     # All files (A/M/D)
    files_added: List[str]       # Files with 'A' status
    files_modified: List[str]    # Files with 'M' status
    files_deleted: List[str]     # Files with 'D' status

    # Stats
    insertions: int              # Lines added
    deletions: int               # Lines removed
    files_count: int             # Total files changed

    # Classification
    is_agent_commit: bool        # Contains Claude Code signature
    is_merge_commit: bool        # Has multiple parents


class SyncOptions(TypedDict, total=False):
    """Options for git sync operation."""
    since: str                   # "90 days", "2025-01-01", etc.
    until: str                   # Upper bound date
    repo_path: str               # Path to git repository
    incremental: bool            # Only sync new commits (default: True)


class SyncResult(TypedDict):
    """Result of sync operation."""
    commits_synced: int
    commits_skipped: int         # Already in DB
    last_hash: str               # Most recent commit synced
    errors: List[str]            # Any parse errors (non-fatal)


class ParseError(Exception):
    """Error parsing git log output."""
    pass


class GitError(Exception):
    """Error running git command."""
    pass


def get_commit_body(commit_hash: str, repo_path: str = ".") -> str:
    """Fetch full commit message body for a single commit.

    Used for agent detection which needs to check the full body.

    Args:
        commit_hash: Full or short commit hash
        repo_path: Path to git repository

    Returns:
        Full commit message (subject + body)
    """
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%B", commit_hash],
            cwd=repo_path,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace"
        )
        if result.returncode == 0:
            return result.stdout
    except Exception:
        pass
    return ""


# ============================================================================
# Agent Commit Detection
# ============================================================================

AGENT_SIGNATURES = [
    "generated with claude code",
    "🤖 generated with",
    "co-authored-by: claude",
]


def detect_agent_commit(message: str) -> bool:
    """Detect if commit was generated by Claude Code.

    Checks commit message for known signatures.

    Args:
        message: Commit message (can be multi-line)

    Returns:
        True if commit appears to be agent-generated
    """
    message_lower = message.lower()
    for signature in AGENT_SIGNATURES:
        if signature in message_lower:
            return True
    return False


# ============================================================================
# Commit Parsing
# ============================================================================

def parse_commit_block(block: str) -> GitCommit:
    """Parse a single commit block from git log output.

    A block consists of:
    1. Format line (hash§short§date§name§email§subject§parents)
    2. Empty line (optional)
    3. Numstat lines (insertions\\tdeletions\\tfile)
    4. Empty line (optional)
    5. Name-status lines (M\\tfile or A\\tfile or D\\tfile)

    Args:
        block: Raw text block for one commit

    Returns:
        GitCommit with all fields populated

    Raises:
        ParseError: If block doesn't match expected format
    """
    lines = block.strip().split('\n')

    if not lines:
        raise ParseError("Empty commit block")

    # Line 1: Format string
    format_line = lines[0]
    parts = format_line.split('§')

    if len(parts) != 7:
        raise ParseError(f"Expected 7 parts in format line, got {len(parts)}: {format_line[:100]}")

    hash_full, hash_short, timestamp_str, name, email, subject, parents = parts

    # Parse timestamp
    try:
        timestamp = datetime.fromisoformat(timestamp_str)
    except ValueError:
        # Fallback for different formats
        timestamp = datetime.now()

    # Detect merge commit (multiple parents)
    parent_list = parents.strip().split() if parents.strip() else []
    is_merge = len(parent_list) > 1

    # Parse numstat and name-status lines
    insertions, deletions = 0, 0
    files_added: List[str] = []
    files_modified: List[str] = []
    files_deleted: List[str] = []

    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue

        if '\t' in line:
            parts = line.split('\t')

            # Detect line type based on content, not section order
            # Numstat format: <number>\t<number>\t<filepath> (or -\t-\t for binary)
            # Name-status format: <single-letter>\t<filepath>

            if len(parts) >= 3:
                ins_str, del_str = parts[0], parts[1]
                # Check if this looks like numstat (numbers or -)
                is_numstat = (
                    (ins_str == '-' or ins_str.isdigit()) and
                    (del_str == '-' or del_str.isdigit())
                )
                if is_numstat:
                    # Handle binary files (show - instead of numbers)
                    if ins_str != '-' and ins_str.isdigit():
                        insertions += int(ins_str)
                    if del_str != '-' and del_str.isdigit():
                        deletions += int(del_str)
                    continue

            # Name-status format: status<tab>filepath (or status<tab>oldpath<tab>newpath for renames)
            if len(parts) >= 2:
                status = parts[0]
                # Verify it's a status letter
                if len(status) == 1 and status in 'AMDRC':
                    filepath = parts[-1]  # Use last part (handles renames)

                    if status == 'A':
                        files_added.append(filepath)
                    elif status == 'M':
                        files_modified.append(filepath)
                    elif status == 'D':
                        files_deleted.append(filepath)
                    elif status == 'R':
                        # Rename: treat as modify of new file
                        files_modified.append(filepath)

    all_files = files_added + files_modified + files_deleted

    # Detect agent commit
    is_agent = detect_agent_commit(subject)

    return GitCommit(
        hash=hash_full,
        short_hash=hash_short,
        timestamp=timestamp,
        author_name=name,
        author_email=email,
        message=subject,
        files_changed=all_files,
        files_added=files_added,
        files_modified=files_modified,
        files_deleted=files_deleted,
        insertions=insertions,
        deletions=deletions,
        files_count=len(all_files),
        is_agent_commit=is_agent,
        is_merge_commit=is_merge
    )


def split_commit_blocks(raw_output: str) -> List[str]:
    """Split raw git log output into individual commit blocks.

    Commits are separated by the format line pattern (starts with hash).

    Args:
        raw_output: Raw output from git log command

    Returns:
        List of commit block strings
    """
    blocks = []
    current_block_lines = []

    for line in raw_output.split('\n'):
        # Detect start of new commit (40-char hash followed by §)
        if '§' in line and len(line.split('§')[0]) == 40:
            # Save previous block
            if current_block_lines:
                blocks.append('\n'.join(current_block_lines))
            current_block_lines = [line]
        else:
            current_block_lines.append(line)

    # Don't forget last block
    if current_block_lines:
        blocks.append('\n'.join(current_block_lines))

    return blocks


# ============================================================================
# Database Operations
# ============================================================================

def get_last_synced_hash(db: Connection) -> Optional[str]:
    """Get the most recent commit hash in database.

    Used for incremental sync - only fetch commits after this.

    Args:
        db: SQLite database connection

    Returns:
        Hash string or None if database empty
    """
    cursor = db.execute("""
        SELECT hash FROM git_commits
        ORDER BY timestamp DESC
        LIMIT 1
    """)
    row = cursor.fetchone()
    return row[0] if row else None


def commit_exists(db: Connection, commit_hash: str) -> bool:
    """Check if commit already exists in database.

    Args:
        db: SQLite database connection
        commit_hash: Full commit hash to check

    Returns:
        True if commit exists
    """
    cursor = db.execute(
        "SELECT 1 FROM git_commits WHERE hash = ?",
        (commit_hash,)
    )
    return cursor.fetchone() is not None


def insert_commit(db: Connection, commit: GitCommit) -> None:
    """Insert a commit into the database.

    Args:
        db: SQLite connection
        commit: Parsed commit object
    """
    db.execute("""
        INSERT INTO git_commits (
            hash, short_hash, timestamp, message,
            author_name, author_email,
            files_changed, files_added, files_deleted, files_modified,
            insertions, deletions, files_count,
            is_agent_commit, is_merge_commit
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        commit.hash,
        commit.short_hash,
        commit.timestamp.isoformat(),
        commit.message,
        commit.author_name,
        commit.author_email,
        json.dumps(commit.files_changed),
        json.dumps(commit.files_added),
        json.dumps(commit.files_deleted),
        json.dumps(commit.files_modified),
        commit.insertions,
        commit.deletions,
        commit.files_count,
        commit.is_agent_commit,
        commit.is_merge_commit
    ))


# ============================================================================
# Main Sync Function
# ============================================================================

def sync_commits(
    db: Connection,
    options: SyncOptions
) -> SyncResult:
    """Sync git commits to SQLite database.

    Args:
        db: SQLite database connection
        options: Sync configuration

    Returns:
        SyncResult with counts and status
    """
    repo_path = options.get("repo_path", ".")

    # Build git log command
    # Format: hash§short§date§name§email§subject§parents
    # Note: Using %s (subject only) for the format line
    # Agent detection needs full body, so we'll fetch that separately
    cmd = [
        "git", "log",
        "--format=%H§%h§%aI§%an§%ae§%s§%P",
        "--numstat",
        "--name-status",
    ]

    if options.get("since"):
        cmd.extend(["--since", options["since"]])

    if options.get("until"):
        cmd.extend(["--until", options["until"]])

    # For incremental sync, we'll check hashes as we go
    last_hash = None
    if options.get("incremental", True):
        last_hash = get_last_synced_hash(db)

    # Execute git log
    try:
        result = subprocess.run(
            cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace"
        )
    except FileNotFoundError:
        raise GitError("git command not found")

    if result.returncode != 0:
        raise GitError(f"git log failed: {result.stderr}")

    # Split into commit blocks
    raw_output = result.stdout
    blocks = split_commit_blocks(raw_output)

    # Parse and insert
    synced = 0
    skipped = 0
    errors: List[str] = []
    newest_hash = ""

    for block in blocks:
        if not block.strip():
            continue

        try:
            commit = parse_commit_block(block)

            # Stop at last synced (incremental)
            if last_hash and commit.hash == last_hash:
                break

            # Check if already exists
            if commit_exists(db, commit.hash):
                skipped += 1
                continue

            # Check full body for agent detection (subject only isn't enough)
            if not commit.is_agent_commit:
                full_body = get_commit_body(commit.hash, repo_path)
                if detect_agent_commit(full_body):
                    commit = GitCommit(
                        hash=commit.hash,
                        short_hash=commit.short_hash,
                        timestamp=commit.timestamp,
                        author_name=commit.author_name,
                        author_email=commit.author_email,
                        message=commit.message,
                        files_changed=commit.files_changed,
                        files_added=commit.files_added,
                        files_modified=commit.files_modified,
                        files_deleted=commit.files_deleted,
                        insertions=commit.insertions,
                        deletions=commit.deletions,
                        files_count=commit.files_count,
                        is_agent_commit=True,  # Updated
                        is_merge_commit=commit.is_merge_commit
                    )

            # Insert
            insert_commit(db, commit)
            synced += 1

            if not newest_hash:
                newest_hash = commit.hash

        except ParseError as e:
            errors.append(str(e))
            logger.warning(f"Parse error: {e}")
            continue

    db.commit()

    return SyncResult(
        commits_synced=synced,
        commits_skipped=skipped,
        last_hash=newest_hash,
        errors=errors
    )
