//! Git commit sync to SQLite database.
//!
//! Syncs git log data to SQLite for unified querying with file events and Claude sessions.
//!
//! Port of Python `capture/git_sync.py`.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ============================================================================
// Type Definitions
// ============================================================================

/// Parsed git commit with all metadata.
/// Maps 1:1 to Python GitCommit dataclass.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitCommit {
    /// Full 40-char hash
    pub hash: String,
    /// First 7 chars
    pub short_hash: String,
    /// Author date (ISO8601)
    pub timestamp: DateTime<Utc>,
    /// Author name
    pub author_name: String,
    /// Author email
    pub author_email: String,
    /// Commit message (first line / subject)
    pub message: String,
    /// All files changed (A/M/D combined)
    pub files_changed: Vec<String>,
    /// Files with 'A' status
    pub files_added: Vec<String>,
    /// Files with 'M' status
    pub files_modified: Vec<String>,
    /// Files with 'D' status
    pub files_deleted: Vec<String>,
    /// Lines added
    pub insertions: i32,
    /// Lines removed
    pub deletions: i32,
    /// Total files changed count
    pub files_count: i32,
    /// True if commit contains Claude Code signature
    pub is_agent_commit: bool,
    /// True if commit has multiple parents
    pub is_merge_commit: bool,
}

/// Options for git sync operation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SyncOptions {
    /// Time range: "90 days", "2025-01-01", etc.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since: Option<String>,
    /// Upper bound date
    #[serde(skip_serializing_if = "Option::is_none")]
    pub until: Option<String>,
    /// Path to git repository (default: ".")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub repo_path: Option<String>,
    /// Only sync new commits (default: true)
    #[serde(default = "default_true")]
    pub incremental: bool,
}

fn default_true() -> bool {
    true
}

/// Result of sync operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncResult {
    /// Number of commits successfully synced
    pub commits_synced: i32,
    /// Number of commits skipped (already in DB)
    pub commits_skipped: i32,
    /// Hash of most recent commit synced
    pub last_hash: String,
    /// Non-fatal parse errors
    pub errors: Vec<String>,
}

// ============================================================================
// Agent Commit Detection
// ============================================================================

/// Agent commit detection signatures.
/// Patterns that indicate a commit was generated by Claude Code.
pub const AGENT_SIGNATURES: &[&str] = &[
    "generated with claude code",
    "🤖 generated with",
    "co-authored-by: claude",
];

/// Detect if commit message contains Claude Code signature.
///
/// Checks commit message for known signatures (case-insensitive).
///
/// # Arguments
/// * `message` - Commit message (can be multi-line)
///
/// # Returns
/// `true` if commit appears to be agent-generated
pub fn detect_agent_commit(message: &str) -> bool {
    let message_lower = message.to_lowercase();
    AGENT_SIGNATURES
        .iter()
        .any(|sig| message_lower.contains(sig))
}

// ============================================================================
// Commit Parsing
// ============================================================================

/// Parse error for git log output.
#[derive(Debug, Clone)]
pub struct ParseError {
    pub message: String,
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ParseError: {}", self.message)
    }
}

impl std::error::Error for ParseError {}

/// Parse a single commit block from git log output.
///
/// A block consists of:
/// 1. Format line (hash§short§date§name§email§subject§parents)
/// 2. Empty line (optional)
/// 3. Numstat lines (insertions\tdeletions\tfile)
/// 4. Empty line (optional)
/// 5. Name-status lines (M\tfile or A\tfile or D\tfile)
///
/// # Arguments
/// * `block` - Raw text block for one commit
///
/// # Returns
/// `GitCommit` with all fields populated
pub fn parse_commit_block(block: &str) -> Result<GitCommit, ParseError> {
    let lines: Vec<&str> = block.trim().lines().collect();

    if lines.is_empty() {
        return Err(ParseError {
            message: "Empty commit block".to_string(),
        });
    }

    // Line 1: Format string
    let format_line = lines[0];
    let parts: Vec<&str> = format_line.split('§').collect();

    if parts.len() != 7 {
        return Err(ParseError {
            message: format!(
                "Expected 7 parts in format line, got {}: {}",
                parts.len(),
                &format_line[..format_line.len().min(100)]
            ),
        });
    }

    let hash_full = parts[0].to_string();
    let hash_short = parts[1].to_string();
    let timestamp_str = parts[2];
    let name = parts[3].to_string();
    let email = parts[4].to_string();
    let subject = parts[5].to_string();
    let parents = parts[6];

    // Parse timestamp
    let timestamp = chrono::DateTime::parse_from_rfc3339(timestamp_str)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|_| Utc::now());

    // Detect merge commit (multiple parents)
    let parent_list: Vec<&str> = parents.split_whitespace().collect();
    let is_merge = parent_list.len() > 1;

    // Parse numstat and name-status lines
    let mut insertions = 0;
    let mut deletions = 0;
    let mut files_added: Vec<String> = Vec::new();
    let mut files_modified: Vec<String> = Vec::new();
    let mut files_deleted: Vec<String> = Vec::new();

    for line in lines.iter().skip(1) {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        if line.contains('\t') {
            let parts: Vec<&str> = line.split('\t').collect();

            // Detect line type based on content
            // Numstat format: <number>\t<number>\t<filepath> (or -\t-\t for binary)
            // Name-status format: <single-letter>\t<filepath>

            if parts.len() >= 3 {
                let ins_str = parts[0];
                let del_str = parts[1];

                // Check if this looks like numstat (numbers or -)
                let is_numstat = (ins_str == "-" || ins_str.parse::<i32>().is_ok())
                    && (del_str == "-" || del_str.parse::<i32>().is_ok());

                if is_numstat {
                    // Handle binary files (show - instead of numbers)
                    if ins_str != "-" {
                        if let Ok(n) = ins_str.parse::<i32>() {
                            insertions += n;
                        }
                    }
                    if del_str != "-" {
                        if let Ok(n) = del_str.parse::<i32>() {
                            deletions += n;
                        }
                    }
                    continue;
                }
            }

            // Name-status format: status<tab>filepath (or status<tab>oldpath<tab>newpath for renames)
            if parts.len() >= 2 {
                let status = parts[0];
                // Verify it's a status letter
                if status.len() == 1 && "AMDRC".contains(status) {
                    let filepath = parts.last().unwrap().to_string(); // Use last part (handles renames)

                    match status {
                        "A" => files_added.push(filepath),
                        "M" => files_modified.push(filepath),
                        "D" => files_deleted.push(filepath),
                        "R" => files_modified.push(filepath), // Rename: treat as modify of new file
                        _ => {}
                    }
                }
            }
        }
    }

    let mut all_files = Vec::new();
    all_files.extend(files_added.iter().cloned());
    all_files.extend(files_modified.iter().cloned());
    all_files.extend(files_deleted.iter().cloned());

    // Detect agent commit
    let is_agent = detect_agent_commit(&subject);

    Ok(GitCommit {
        hash: hash_full,
        short_hash: hash_short,
        timestamp,
        author_name: name,
        author_email: email,
        message: subject,
        files_changed: all_files.clone(),
        files_added,
        files_modified,
        files_deleted,
        insertions,
        deletions,
        files_count: all_files.len() as i32,
        is_agent_commit: is_agent,
        is_merge_commit: is_merge,
    })
}

/// Split raw git log output into individual commit blocks.
///
/// Commits are separated by the format line pattern (starts with 40-char hash).
///
/// # Arguments
/// * `raw_output` - Raw output from git log command
///
/// # Returns
/// List of commit block strings
pub fn split_commit_blocks(raw_output: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current_block_lines: Vec<&str> = Vec::new();

    for line in raw_output.lines() {
        // Detect start of new commit (40-char hash followed by §)
        let parts: Vec<&str> = line.split('§').collect();
        let is_new_commit = parts.len() > 1
            && parts[0].len() == 40
            && parts[0].chars().all(|c| c.is_ascii_hexdigit());

        if is_new_commit {
            // Save previous block
            if !current_block_lines.is_empty() {
                blocks.push(current_block_lines.join("\n"));
            }
            current_block_lines = vec![line];
        } else {
            current_block_lines.push(line);
        }
    }

    // Don't forget last block
    if !current_block_lines.is_empty() {
        blocks.push(current_block_lines.join("\n"));
    }

    blocks
}

// ============================================================================
// Git Operations
// ============================================================================

use std::path::Path;
use std::process::Command;

/// Error running git command.
#[derive(Debug, Clone)]
pub struct GitError {
    pub message: String,
}

impl std::fmt::Display for GitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "GitError: {}", self.message)
    }
}

impl std::error::Error for GitError {}

/// Fetch full commit message body for a single commit.
///
/// Used for agent detection which needs to check the full body.
pub fn get_commit_body(commit_hash: &str, repo_path: &Path) -> String {
    let result = Command::new("git")
        .args(["log", "-1", "--format=%B", commit_hash])
        .current_dir(repo_path)
        .output();

    match result {
        Ok(output) if output.status.success() => {
            String::from_utf8_lossy(&output.stdout).to_string()
        }
        _ => String::new(),
    }
}

/// Sync git commits from repository.
///
/// Runs `git log` and parses commits. Does NOT write to database.
/// Caller is responsible for database operations.
///
/// # Arguments
/// * `options` - Sync configuration (since, until, repo_path)
///
/// # Returns
/// * List of parsed commits
pub fn sync_commits(options: &SyncOptions) -> Result<(Vec<GitCommit>, SyncResult), GitError> {
    let repo_path = options.repo_path.as_deref().unwrap_or(".");

    // Build git log command
    // Format: hash§short§date§name§email§subject§parents
    let mut cmd = Command::new("git");
    cmd.args([
        "log",
        "--format=%H§%h§%aI§%an§%ae§%s§%P",
        "--numstat",
        "--name-status",
    ]);

    if let Some(ref since) = options.since {
        cmd.args(["--since", since]);
    }

    if let Some(ref until) = options.until {
        cmd.args(["--until", until]);
    }

    cmd.current_dir(repo_path);

    // Execute git log
    let output = cmd.output().map_err(|e| GitError {
        message: format!("git command failed: {}", e),
    })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(GitError {
            message: format!("git log failed: {}", stderr),
        });
    }

    let raw_output = String::from_utf8_lossy(&output.stdout);

    // Split into commit blocks
    let blocks = split_commit_blocks(&raw_output);

    // Parse commits
    let mut commits = Vec::new();
    let mut errors = Vec::new();
    let mut newest_hash = String::new();

    for block in blocks {
        if block.trim().is_empty() {
            continue;
        }

        match parse_commit_block(&block) {
            Ok(mut commit) => {
                // Check full body for agent detection (subject only isn't enough)
                if !commit.is_agent_commit {
                    let full_body = get_commit_body(&commit.hash, Path::new(repo_path));
                    if detect_agent_commit(&full_body) {
                        commit.is_agent_commit = true;
                    }
                }

                if newest_hash.is_empty() {
                    newest_hash.clone_from(&commit.hash);
                }
                commits.push(commit);
            }
            Err(e) => {
                errors.push(e.message);
            }
        }
    }

    let result = SyncResult {
        commits_synced: commits.len() as i32,
        commits_skipped: 0, // Will be updated by caller after DB check
        last_hash: newest_hash,
        errors,
    };

    Ok((commits, result))
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // detect_agent_commit tests (TDD RED - these should FAIL initially)
    // ========================================================================

    #[test]
    fn test_detect_agent_commit_finds_claude_code_signature() {
        // Standard Claude Code commit message
        assert!(detect_agent_commit(
            "feat: add feature\n\n🤖 Generated with Claude Code"
        ));
    }

    #[test]
    fn test_detect_agent_commit_finds_co_authored_by() {
        // Co-authored-by format
        assert!(detect_agent_commit(
            "fix: bug fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
        ));
    }

    #[test]
    fn test_detect_agent_commit_case_insensitive() {
        // Should be case-insensitive
        assert!(detect_agent_commit(
            "feat: add\n\nGENERATED WITH CLAUDE CODE"
        ));
        assert!(detect_agent_commit(
            "feat: add\n\nGenerated With Claude Code"
        ));
    }

    #[test]
    fn test_detect_agent_commit_returns_false_for_regular_commit() {
        // Regular human commit
        assert!(!detect_agent_commit("feat: add new feature"));
        assert!(!detect_agent_commit("fix: resolve bug in login"));
        assert!(!detect_agent_commit(""));
    }

    #[test]
    fn test_detect_agent_commit_multiline_body() {
        // Signature can be anywhere in the message
        let message = r#"feat: implement authentication

This commit adds user authentication using JWT tokens.
The implementation includes login, logout, and token refresh.

Co-Authored-By: Claude <noreply@anthropic.com>"#;
        assert!(detect_agent_commit(message));
    }

    // ========================================================================
    // parse_commit_block tests (TDD RED - these should FAIL initially)
    // ========================================================================

    #[test]
    fn test_parse_commit_block_extracts_all_fields() {
        let block = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Test Author§test@example.com§feat: add feature§parent123
1	0	src/main.rs
A	src/main.rs"#;

        let commit = parse_commit_block(block).expect("Should parse");
        assert_eq!(commit.short_hash, "abc1234");
        assert_eq!(commit.author_name, "Test Author");
        assert_eq!(commit.author_email, "test@example.com");
        assert_eq!(commit.message, "feat: add feature");
        assert_eq!(commit.insertions, 1);
        assert_eq!(commit.deletions, 0);
        assert_eq!(commit.files_added, vec!["src/main.rs"]);
    }

    #[test]
    fn test_parse_commit_block_handles_merge_commit() {
        let block = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Test Author§test@example.com§Merge branch 'main'§parent1 parent2"#;

        let commit = parse_commit_block(block).expect("Should parse");
        assert!(commit.is_merge_commit);
    }

    #[test]
    fn test_parse_commit_block_handles_modified_files() {
        let block = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Test Author§test@example.com§fix: bug§parent123
5	2	src/lib.rs
M	src/lib.rs"#;

        let commit = parse_commit_block(block).expect("Should parse");
        assert_eq!(commit.files_modified, vec!["src/lib.rs"]);
        assert_eq!(commit.insertions, 5);
        assert_eq!(commit.deletions, 2);
    }

    #[test]
    fn test_parse_commit_block_handles_deleted_files() {
        let block = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Test Author§test@example.com§chore: cleanup§parent123
0	10	old_file.rs
D	old_file.rs"#;

        let commit = parse_commit_block(block).expect("Should parse");
        assert_eq!(commit.files_deleted, vec!["old_file.rs"]);
    }

    #[test]
    fn test_parse_commit_block_detects_agent_commit() {
        let block = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Test Author§test@example.com§feat: add 🤖 Generated with Claude Code§parent123"#;

        let commit = parse_commit_block(block).expect("Should parse");
        assert!(commit.is_agent_commit);
    }

    #[test]
    fn test_parse_commit_block_errors_on_invalid_format() {
        let block = "not a valid commit block";
        assert!(parse_commit_block(block).is_err());
    }

    // ========================================================================
    // split_commit_blocks tests (TDD RED - these should FAIL initially)
    // ========================================================================

    #[test]
    fn test_split_commit_blocks_separates_by_hash() {
        let raw = r#"abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Author§email§msg1§parent1
1	0	file1.rs
A	file1.rs

def5678901234567890def5678901234567890de§def5678§2026-01-16T09:00:00+00:00§Author§email§msg2§parent2
2	1	file2.rs
M	file2.rs"#;

        let blocks = split_commit_blocks(raw);
        assert_eq!(blocks.len(), 2);
    }

    #[test]
    fn test_split_commit_blocks_handles_empty_input() {
        let blocks = split_commit_blocks("");
        assert!(blocks.is_empty());
    }

    #[test]
    fn test_split_commit_blocks_handles_single_commit() {
        let raw = "abc1234567890abc1234567890abc1234567890ab§abc1234§2026-01-17T10:30:00+00:00§Author§email§msg§parent";
        let blocks = split_commit_blocks(raw);
        assert_eq!(blocks.len(), 1);
    }

    // ========================================================================
    // sync_commits integration tests
    // ========================================================================

    #[test]
    fn test_sync_commits_reads_from_current_repo() {
        // This test runs against the current git repository
        let options = SyncOptions {
            since: Some("7 days".to_string()),
            repo_path: Some(".".to_string()),
            ..Default::default()
        };

        let result = sync_commits(&options);

        // Should succeed (we're in a git repo)
        assert!(result.is_ok(), "sync_commits should succeed in git repo");

        let (commits, sync_result) = result.unwrap();

        // There should be at least some commits in last 7 days
        // (we're actively developing this repo)
        assert!(
            !commits.is_empty() || sync_result.errors.is_empty(),
            "Should parse commits or have no errors"
        );

        // Verify commit structure (if any commits)
        for commit in &commits {
            assert_eq!(commit.hash.len(), 40, "Hash should be 40 chars");
            assert!(
                commit.short_hash.len() >= 7,
                "Short hash should be >= 7 chars"
            );
            assert!(
                !commit.author_name.is_empty(),
                "Author name should not be empty"
            );
        }

        println!(
            "Synced {} commits, {} errors",
            sync_result.commits_synced,
            sync_result.errors.len()
        );
    }

    #[test]
    fn test_sync_commits_handles_nonexistent_repo() {
        let options = SyncOptions {
            repo_path: Some("/nonexistent/repo/path".to_string()),
            ..Default::default()
        };

        let result = sync_commits(&options);

        // Should fail gracefully
        assert!(result.is_err(), "Should error for nonexistent repo");
    }
}
